### ISSUE TITLE
Compile errors in DavisRFM69::initialize()

### ISSUE THREAD

**Issue by Scott216** [dekay/DavisRFM69#4]
I'm trying to compile VP2.ino example with the Arduino IDE v1.05. In the file DavisRFM69.cpp, function DavisRFM69::initialize(), I'm getting compile errors on all the constants, like RF_OPMODE_SEQUENCER_ON.  The error is "was not declared in this scope".  Any idea how to resolve this?

**Comment by dekay** [comment]
Fixed with 77b57e2
