### ISSUE TITLE
Missing #defines

### ISSUE THREAD

**Issue by matricies** [dekay/DavisRFM69#5]
I located the missing RFM69registers.h file but there were still 4 #defines missing and giving "not declared" errors:
     **RF_FDEVMSB_4800** (But *RF_FDEVMSB_5000* is in the RFM69registers.h file.)
     **RF_FDEVLSB_4800** (RF_*FDEVLSB_5000* is there too.)
     **RF_AFCLOWBETA_OFF**
     **REG_TESTAFC**
I couldn't find them defined anywhere in any of the libraries mentioned in the readme or blog. Not sure how to fix this.   :-(

**Comment by scottp** [comment]
I have just found the same problem trying to get this compiled. Any ideas out there?

**Comment by Scott216** [comment]
They were removed from this commit:
https://github.com/LowPowerLab/RFM69/commit/e8a076784954da19acd2009b12e23f15e5894b8d
don't know why

Try using this file:
https://github.com/LowPowerLab/RFM69/blob/2d233df459d404583243d0ceb3c7881f8bb43f3f/RFM69registers.h

**Comment by scottp** [comment]
Ahh looks like RFM69Registers has changed. I will write up a patch. Thanks.

**Comment by dekay** [comment]
Should be fixed in 77b57e2
